
version: '3.7'

services:

  web:
    build: ./code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code/:/usr/src/code/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
    - ./.env.dev

  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=activity
    - POSTGRES_PASSWORD=activity
    - POSTGRES_DB=activity_dev

volumes:
  postgres_data: